In [1]:
import numpy as np
zeta=1.1102230246251565e-16
-2*zeta+zeta**2+zeta**3

-2.220446049250313e-16

In [ ]:
def make_BICM_int(self,N,M,type):
        
        BICM_int=np.arange(N,dtype=int)
        #modify BICM int from simplified to arikan decoder order
        bit_reversal_sequence=self.cd.bit_reversal_sequence
        BICM_int=BICM_int[bit_reversal_sequence]
        
        if type==1:#1:separated scheme 
            pass
        elif type==2:#2:Block intlv(No intlv in arikan polar decoder) 
            BICM_int=np.reshape(BICM_int,[int(np.log2(M**(1/2))),-1],order='C')
            BICM_int[0]=np.sort(BICM_int[0])
            BICM_int[1]=np.sort(BICM_int[1])
            BICM_int=np.ravel(BICM_int,order='C')
            print(BICM_int)
            
        elif type==3:#3:No intlv(Block intlv in arikan polar decoder) 
            BICM_int=np.reshape(BICM_int,[int(np.log2(M**(1/2))),-1],order='C')
            BICM_int=np.ravel(BICM_int,order='F')
        elif type==4:#4:rand intlv
            tmp,_=make_BICM(N)
            BICM_int=BICM_int[tmp]
        elif type==5:#2:Block intlv(No intlv in arikan polar decoder) 
            tmp=np.arange(N//int(np.log2(M**(1/2))),dtype=int)
            random.shuffle(tmp)
            BICM_int=np.reshape(BICM_int,[int(np.log2(M**(1/2))),-1],order='C')
            for i in range (int(np.log2(M**(1/2)))):
                BICM_int[i]=BICM_int[i][tmp]
            BICM_int=np.ravel(BICM_int,order='C')
        elif type==6:
            BICM_int=np.reshape(BICM_int,[int(np.log2(M**(1/2))),-1],order='C')
            for i in range (int(np.log2(M**(1/2)))):
                tmp=np.arange(N//int(np.log2(M**(1/2))),dtype=int)
                random.shuffle(tmp)
                BICM_int[i]=BICM_int[i][tmp]
            BICM_int=np.ravel(BICM_int,order='C')
            
        else:
            print("interleaver type error")
            
        
            
        BICM_deint=np.argsort(BICM_int)
        
        #np.savetxt("deint",BICM_deint,fmt='%.0f')
        
        #print(BICM_int)
        #print(BICM_deint)
        
        return BICM_int,BICM_deint

In [3]:
def llr_preparation(self):
        """ Creates the coordinates
        where either zeros or ones can be placed in the signal constellation..
        Returns
        -------
        zeros : list of lists of complex values
            The coordinates where zeros can be placed in the signal constellation.
        ones : list of lists of complex values
            The coordinates where ones can be placed in the signal constellation.
        """
        code_book = self.code_book

        zeros = [[] for i in range(self.N)]
        ones = [[] for i in range(self.N)]

        bin_seq = self.de2bin(self.m)

        for bin_idx, bin_symb in enumerate(bin_seq):
            if self.bin_input == True:
                key = bin_symb
            else:
                key = bin_idx
            for possition, digit in enumerate(bin_symb):
                if digit == '0':
                    zeros[possition].append(bin_symb)
                else:
                    ones[possition].append(bin_symb)
        return zeros, ones

In [10]:

from modulation.modulation import QAMModem
modem=QAMModem(16)
zeros,ones=llr_preparation(modem)
print(zeros[1])
print(ones[1])

['0000', '0001', '0010', '0011', '1000', '1001', '1010', '1011']
['0100', '0101', '0110', '0111', '1100', '1101', '1110', '1111']


In [36]:
interleaver=np.arange(20)
interleaver=np.reshape(interleaver,[2,-1],order='C')
interleaver=np.ravel(interleaver,order='F')
print(interleaver)

[ 0 10  1 11  2 12  3 13  4 14  5 15  6 16  7 17  8 18  9 19]


In [37]:
a=np.arange(20)

a=np.reshape(a,[2,-1],order='C')
print(a)
map=(a.T@np.array([[1,0],[1,1]]))

print(map)
map=np.ravel(map,order='F')
print(map[interleaver])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[10 10]
 [12 11]
 [14 12]
 [16 13]
 [18 14]
 [20 15]
 [22 16]
 [24 17]
 [26 18]
 [28 19]]
[10 10 12 11 14 12 16 13 18 14 20 15 22 16 24 17 26 18 28 19]


In [38]:
a=np.ravel(a,order='C')[interleaver][:4]

a=np.reshape(a,[2,-1],order='F')
print(a)
map=(a.T@np.array([[1,0],[1,1]]))
map=np.ravel(map,order='C')
print(map)

[[ 0  1]
 [10 11]]
[10 10 12 11]


In [18]:
from modulation.modulation import QAMModem
modem=QAMModem(16)
G_0=np.array([[1,0],[1,1]])
base_num=2

decs=[dec for dec in range(2**2)]
bin_out = [np.binary_repr(d, width=base_num) for d in decs]
bin_out= [np.array(list(bin_out_str),dtype=int) for bin_out_str in bin_out]
print(bin_out)

[array([0, 0]), array([0, 1]), array([1, 0]), array([1, 1])]


In [30]:
2**2**4

65536

In [28]:
a=np.array([1,1],dtype=int)
a=np.array(a,dtype=str)
''.join(a)

'11'

In [8]:
import numpy as np
b=np.arange(10)
print(b)
a=np.empty(0,dtype=int)
a
a=np.block([a,b])
print(a)
a=np.block([a,b])
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]


In [22]:
import time

import ray 
from ray.test.cluster_utils import Cluster

cluster = Cluster(True, True, head_node_args={"num_cpus": 0})
node = cluster.add_node()

@ray.remote(num_cpus=1)
class Foo:
    def ping(self):
        pass

f = Foo.remote()

print("pinging")
ray.get(f.ping.remote())

x = f.ping.remote()

print("removing node")
cluster.remove_node(node)
print("done removing node")

for i in range(100):
    print(i, ray.wait([x], timeout=1))
    time.sleep(1)

ModuleNotFoundError: No module named 'ray.test'

In [23]:

import ray
import time
import random


@ray.remote
def worker_func(pid):
    """各プロセスの実行には3-15秒かかる
    """
    time.sleep(random.randint(3, 15))
    return f"pid {pid} finished"


ray.init()
start = time.time()
work_in_progresses = [worker_func.remote(i) for i in range(10)]
ray.cancel(work_in_progresses[3])
for i in range(10):
    
    finished, work_in_progresses = ray.wait(work_in_progresses, num_returns=1)
    orf = finished[0]
    print(len(finished))
    print(len(work_in_progresses))
    print(ray.get(orf))
    print("Elapsed:", time.time() - start)

RuntimeError: Maybe you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.

In [42]:
import ray
import time
import random


@ray.remote
def worker_func(pid):
    """各プロセスの実行には3-15秒かかる
    """
    time.sleep(random.randint(10, 20))
    
    print(f"not breaked {pid}")
    return f"pid {pid} finished"

#ray.init()
start = time.time()
work_in_progresses = [worker_func.remote(i) for i in range(10)]
tmp=work_in_progresses
for i in range(10):
    finished, work_in_progresses = ray.wait(work_in_progresses, num_returns=1)
    print(len(finished))
    print(len(tmp))  
    orf = finished[0]
    
    print(ray.get(orf))
    print("Elapsed:", time.time() - start)
    
    if i>5:
        for obj in work_in_progresses:
            ray.cancel(obj,force=False)
        del work_in_progresses
        
        break

#print("break")
#finished, work_in_progresses = ray.wait(work_in_progresses, num_returns=1)    
#orf = finished[0]

#print(ray.get(orf))
#print("Elapsed:", time.time() - start)

1
10
pid 1 finished
Elapsed: 10.0430326461792
(worker_func pid=2331903) not breaked 1
1
10
pid 5 finished
Elapsed: 11.015307664871216
(worker_func pid=2331886) not breaked 5
1
10
pid 4 finished
Elapsed: 14.075342655181885
(worker_func pid=2331908) not breaked 4
1
10
pid 8 finished
Elapsed: 15.163508176803589
(worker_func pid=2331895) not breaked 8
1
10
pid 0 finished
Elapsed: 18.08168864250183
(worker_func pid=2331905) not breaked 0
1
10
pid 2 finished
Elapsed: 19.099491834640503
(worker_func pid=2331915) not breaked 2
1
10
pid 7 finished
Elapsed: 20.061918020248413


(worker_func pid=2331882) not breaked 7


2022-06-13 18:53:42,132	ERROR worker.py:289 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::worker_func() (pid=2331912, ip=133.34.30.166)
  File "/tmp/ipykernel_2330913/2530618250.py", line 10, in worker_func
KeyboardInterrupt

During handling of the above exception, another exception occurred:

ray::worker_func() (pid=2331912, ip=133.34.30.166)
ray.exceptions.TaskCancelledError: Task: TaskID(5d624e85d2955067ffffffffffffffffffffffff01000000) was cancelled
2022-06-13 18:53:42,133	ERROR worker.py:289 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::worker_func() (pid=2331877, ip=133.34.30.166)
  File "/tmp/ipykernel_2330913/2530618250.py", line 10, in worker_func
KeyboardInterrupt

During handling of the above exception, another exception occurred:

ray::worker_func() (pid=2331877, ip=133.34.30.166)
ray.exceptions.TaskCancelledError: Task: TaskID(dd4376bd3c667794ffffffffffffffffffffffff01000000) was cancelled
2022-06-13 18:53:42,135	ERROR 

In [8]:
a=[1,2,3]
b=[a,a,a]
print(b)


[[1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [10]:
del b
print(b)

NameError: name 'b' is not defined

In [1]:
from pprint import pprint
import ray

ray.shutdown()
ray.init()

2022-06-09 23:39:49,739	INFO services.py:1477 -- View the Ray dashboard at http://127.0.0.1:8265


RayContext(dashboard_url='127.0.0.1:8265', python_version='3.8.10', ray_version='3.0.0.dev0', ray_commit='65d7a610ab3b4ca455ab82503da0a8a9947b22a6', address_info={'node_ip_address': '133.34.30.166', 'raylet_ip_address': '133.34.30.166', 'redis_address': None, 'object_store_address': '/tmp/ray/session_2022-06-09_23-39-47_391795_2639484/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2022-06-09_23-39-47_391795_2639484/sockets/raylet', 'webui_url': '127.0.0.1:8265', 'session_dir': '/tmp/ray/session_2022-06-09_23-39-47_391795_2639484', 'metrics_export_port': 62546, 'gcs_address': '133.34.30.166:60002', 'address': '133.34.30.166:60002', 'node_id': 'dd3495dd110992aa6f884ac785e48720f3007d7bf4e5c4a8a87e0417'})

In [ ]:
import cupy
def process_0():
    import cupyx.distributed
    cupy.cuda.Device(0).use()
    comm = cupyx.distributed.init_process_group(2, 0)
    array = cupy.ones(1)
    comm.broadcast(array, 0)

def process_1():
    import cupyx.distributed
    cupy.cuda.Device(1).use()
    comm = cupyx.distributed.init_process_group(2, 1)
    array = cupy.zeros(1)
    comm.broadcast(array, 0)
    cupy.equal(array, cupy.ones(1))

In [ ]:
process_0()

In [ ]:
2**(2*8)

In [ ]:
import numpy as np
a=np.array([2,4,6,3,5])
print(np.argsort(a))
a=a[[1,0,2,3,4]]
print(a)
np.argsort(a)

In [ ]:
def calc_J_inv(I):
    '''
    input:
    I:mutual information
    output:
    gamma:channel SNR Es/No
    ----
    referrence:
    POLAR CODES FOR ERROR CORRECTION:
    ANALYSIS AND DECODING ALGORITHMS
    p37
    (4.5)
    '''
    if I>1 or I<0:
        print("I is err")
    
    a1=1.09542
    b1=0.214217
    c1=2.33727
    a2=0.706692
    b2=0.386013
    c2=-1.75017
    I_thresh=0.3646
    
    if I<I_thresh:
        sigma=a1*I**2+b1*I+c1*I**(1/2)
    else:
        sigma=-a2*np.log(b2*(1-I))-c2*I
        
    gamma=sigma**2/8
    #gamma_dB=10*math.log10(gamma)
    return gamma

In [1]:
import numpy as np
import matplotlib.pyplot as plt
y=np.arange(0,1,0.03)
x=np.zeros(len(y))
for i in range(len(y)):
    x[i]=calc_J_inv(y[i])
    
x=10*np.log10(x)
plt.plot(x,y)

filename="J_inverse_function"
with open(filename,'w') as f:
    for i in range(len(x)):
        print(str(x[i]),str(y[i]),file=f)



NameError: name 'calc_J_inv' is not defined

In [24]:
def reverse(index,n):
    '''
    make n into bit reversal order
    '''
    tmp=format (index,'b')
    tmp=tmp.zfill(n+1)[:0:-1]
    res=int(tmp,2) 
    return res

In [45]:
import numpy as np
N=1024
K=512
M=256
EsNodB=9.0
dmin=(6/(M-1))**(1/2)
gamma=10**(EsNodB/10)*dmin/2

gammadb=10*np.log10(gamma)
print(gammadb)

-2.1522446068913688


In [48]:

n=int(np.log2(N))

filename=str(-2.2)+'.dat'
print(filename)
a=np.loadtxt(filename,dtype=str)
xi=np.zeros(N)
print(a)
xi=a[:,1].astype(float)

-2.2.dat
[['0,' '-1.988294e+03']
 ['1,' '-3.986529e+02']
 ['2,' '-5.493686e+02']
 ...
 ['1021,' '2.283489e+01']
 ['1022,' '2.157829e+01']
 ['1023,' '2.795075e+01']]


In [49]:
tmp=np.argsort(xi)
frozen_bits=np.sort(tmp[:N-K])
info_bits=np.sort(tmp[N-K:])
#bit reversal order
for i in range(len(frozen_bits)):
    frozen_bits[i]=reverse(frozen_bits[i],n)
    
frozen_bits=np.sort(frozen_bits)
    
for i in range(len(info_bits)):
    info_bits[i]=reverse(info_bits[i],n)
info_bits=np.sort(info_bits)


In [50]:
from polar_code.RCA import RCA
const=RCA()
a1,b1=const.main_const(N,K,EsNodB,256)
a,b=const.main_const(N,K,gammadb,2)
print(np.sum(a1!=a))


dmin=(6/(M-1))**(1/2)
gamma=10**(EsNodB/10)*dmin/2 #QPSK(sqrt(2))
#gamma=gamma*np.ones(N)


0


In [51]:
from polar_code.iGA import Improved_GA

const=Improved_GA()
c,d=const.main_const(N,K,EsNodB,256)

In [52]:
print(np.sum(a!=frozen_bits))
print(np.sum(c!=frozen_bits))
print(np.sum(c!=a))
#print(a)
#print(frozen_bits)

0
277
277


In [57]:
M=256
import math
for i in range(0,int(math.log2(M)))[::-1]:
    print(i)

7
6
5
4
3
2
1
0


In [54]:
const=0
for i in range(len(a)):
    if np.any(a[i]==frozen_bits)==False:
        const+=1

print(const)

const=0
for i in range(len(c)):
    if np.any(c[i]==frozen_bits)==False:
        const+=1

print(const)


const=0
for i in range(len(c)):
    if np.any(c[i]==a)==False:
        const+=1

print(const)

0
2
2


In [1]:
import numpy as np

In [18]:
z1=-800
c=np.log(np.exp(z1)+np.exp(z1)-np.exp(z1+z1))

/tmp/ipykernel_844390/39805590.py:2: RuntimeWarning: divide by zero encountered in log
  c=np.log(np.exp(z1)+np.exp(z1)-np.exp(z1+z1))


In [23]:
def make_BICM_int(type):
    N=1024
    M=4
    
    if type==1:#1:separated scheme 
        print("interleaver type error!")
    elif type==2:#2:Block intlv(No intlv in arikan polar decoder) 
        BICM_int=np.arange(N,dtype=int)
    elif type==3:#3:No intlv(Block intlv in arikan polar decoder) 
        BICM_int=np.arange(N,dtype=int)
        BICM_int=np.reshape(BICM_int,[int(np.log2(M)),-1],order='C')
        BICM_int=np.ravel(BICM_int,order='F')
    elif type==4:#4:rand intlv
        BICM_int=np.arange(N,dtype=int)
        random.shuffle(BICM_int)
        
    #modify BICM int from simplified to arikan decoder order
    BICM_int=np.reshape(BICM_int,[2,-1],order='F')
    BICM_int=np.ravel(BICM_int,order='C')
    
    BICM_deint=np.argsort(BICM_int)
    
    return BICM_int,BICM_deint

In [24]:
import numpy as np
make_BICM_int(2)

(array([   0,    2,    4, ..., 1019, 1021, 1023]),
 array([   0,  512,    1, ..., 1022,  511, 1023]))

In [57]:
import numpy as np
CHECK_NODE_TANH_THRES=37.98

def max_str(a,b):
    res=max(a,b)
    res+=np.log(1+np.exp(-1*abs(a-b)))
    return res

llr_list=np.arange(-50,-30,0.1)
for llr_1 in llr_list:
    #llr_1=CHECK_NODE_TANH_THRES
    llr_2=30
    if abs(llr_1) > CHECK_NODE_TANH_THRES and abs(llr_2) > CHECK_NODE_TANH_THRES:
        
        if llr_1 * llr_2 > 0:
            # If both LLRs are of one sign, we return the minimum of their absolute values.
            res=min(abs(llr_1), abs(llr_2))
        else:
            # Otherwise, we return an opposite to the minimum of their absolute values.
            res=-1 * min(abs(llr_1), abs(llr_2))
        #tmp=np.log(np.exp(-1*res)+np.exp(llr_1+llr_2-res))-np.log(np.exp(llr_1)+np.exp(llr_2))
        tmp=max_str(-1*res,llr_1+llr_2-res)-max_str(llr_1,llr_2)
        print(tmp)
    else:
        res= 2 * np.arctanh(np.tanh(llr_1 / 2, ) * np.tanh(llr_2 / 2))