In [24]:
import numpy as np
from modulation import QAMModem

In [58]:
a=np.arange(20)

a=np.reshape(a,[2,10])

b=np.array([[1,0],[1,1]])
print(a)
c=a.T@b
print(c)
np.ravel(c.T,order='C')

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[10 10]
 [12 11]
 [14 12]
 [16 13]
 [18 14]
 [20 15]
 [22 16]
 [24 17]
 [26 18]
 [28 19]]


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [55]:
print(c.shape)

d=np.arange(40)

d=np.reshape(d,[10,2,2])

print(d[:,:,0])
d=d[:,:,0]
d*c


(10, 2)
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]
 [20 22]
 [24 26]
 [28 30]
 [32 34]
 [36 38]]


array([[ 0,  0],
       [ 0,  6],
       [ 0,  0],
       [ 0, 14],
       [ 0,  0],
       [ 0, 22],
       [ 0,  0],
       [ 0, 30],
       [ 0,  0],
       [ 0, 38]])

In [2]:
modem=QAMModem(16)

In [3]:
modem.code_book

{'0000': (-0.9486832980505138+0.9486832980505138j),
 '0001': (-0.9486832980505138+0.31622776601683794j),
 '0011': (-0.9486832980505138-0.31622776601683794j),
 '0010': (-0.9486832980505138-0.9486832980505138j),
 '0110': (-0.31622776601683794-0.9486832980505138j),
 '0111': (-0.31622776601683794-0.31622776601683794j),
 '0101': (-0.31622776601683794+0.31622776601683794j),
 '0100': (-0.31622776601683794+0.9486832980505138j),
 '1100': (0.31622776601683794+0.9486832980505138j),
 '1101': (0.31622776601683794+0.31622776601683794j),
 '1111': (0.31622776601683794-0.31622776601683794j),
 '1110': (0.31622776601683794-0.9486832980505138j),
 '1010': (0.9486832980505138-0.9486832980505138j),
 '1011': (0.9486832980505138-0.31622776601683794j),
 '1001': (0.9486832980505138+0.31622776601683794j),
 '1000': (0.9486832980505138+0.9486832980505138j)}

In [20]:
""" Creates the coordinates
where either zeros or ones can be placed in the signal constellation..
Returns
-------
zeros : list of lists of complex values
    The coordinates where zeros can be placed in the signal constellation.
ones : list of lists of complex values
    The coordinates where ones can be placed in the signal constellation.
"""
code_book = self.code_book

zeros = [[] for i in range(self.N)]
ones = [[] for i in range(self.N)]

bin_seq = self.de2bin(self.m)

for bin_idx, bin_symb in enumerate(bin_seq):
    if self.bin_input == True:
        key = bin_symb
    else:
        key = bin_idx
    for possition, digit in enumerate(bin_symb):
        if digit == '0':
            zeros[possition].append(code_book[key])
        else:
            ones[possition].append(code_book[key])

<class 'list'>


In [22]:
modem.zeros=zeros
modem.ones=ones